libmtd: add Memory Technology Device (MTD) Interface
phoenix-rtos/phoenix-rtos-corelibs pull request #12
Opened 2022-04-08 14:49 UTC by HBuczynski

## Description

Library for Memory Technology Device (MTD) Interface. This PR provides basic functionality of MTD device which has been tested in `jffs2` filesystem.

DTR-102, PD-216

## Motivation and Context

The library provides an abstraction layer for NOR and NAND flash memories used by filesystems and `mtd-utils` tools to manage raw operations on flash memories.

To provide appropriate interface for `mtd-utils`, additional structures have to be added (based on the linux interface):
 - [mtd-abi](https://github.com/torvalds/linux/blob/master/include/uapi/mtd/mtd-abi.h)
 - [mtd-user](https://github.com/torvalds/linux/blob/master/include/uapi/mtd/mtd-user.h)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## How Has This Been Tested?

- [ ] Already covered by automatic testing.
- [ ] New test added: (add PR link here).
- [x] Tested by hand on: (zynq7000).

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing linter checks and tests passed.
- [ ] My changes generate no new compilation warnings for any of the targets.

## Special treatment

- [x] This PR needs additional PRs to work (https://github.com/phoenix-rtos/libphoenix/pull/174).
- [x] I will merge this PR by myself when appropriate.

2022-04-11 13:31 UTC, agkaminski requested changes
MISRA related remarks applies to the whole PR

2022-04-12 08:33 UTC, HBuczynski commented on libmtd/include/mtd/mtd.h
> +extern int mtd_is_locked(struct mtd_info *mtd, off_t ofs, uint64_t len);
Yes, there are standard functions name used by `jffs2` and other tools.

2022-04-12 09:27 UTC, HBuczynski commented on libmtd/mtd.c
> +	if (!instr->len) {
Which rule define this?
`!` is a logical operand which returns `true` or `false`. The `Rule 14.4` says:

> The controlling expression of an if statement and the controlling
expression of an iteration- statement shall have essentially Boolean type

Moreover, I have seen in the other PRs that such statements were accepted.

2022-04-12 11:14 UTC, HBuczynski commented on libmtd/mtd.c
> +		return -EOPNOTSUPP;
Thanks for comment.
I have changed the code in the whole PR to be consistent with MISRA rules.

2022-04-12 11:20 UTC, agkaminski commented on libmtd/mtd.c
> +	}
One exit path and code repetition less
```suggestion
	if (instr->len == 0) {
		instr->state = MTD_ERASE_DONE;
	}
	else {
		instr->state = MTD_ERASE_PENDING;
		res = mtd->ops->erase(mtdInfo->storage, instr->addr, instr->len);
		if (res < 0) {
			instr->fail_addr = instr->addr;
			instr->state = MTD_ERASE_FAILED;
		}
		else {
			instr->state = MTD_ERASE_DONE;
		}
	}

	if (instr->callback != NULL) {
		instr->callback(instr);
	}
```

2022-04-12 11:20 UTC, agkaminski commented on libmtd/mtd.c
> +	return mtd->ops->point(mtdInfo->storage, from, len, retlen, virt, phys);
Avoiding multiple exit paths
```suggestion
	if (mtd->ops->point == NULL) {
		ret = -EOPNOTSUPP;
	}
	else if (from < 0 || from >= mtdInfo->size || len > (mtdInfo->size - from)) {
		ret = -EINVAL;
	}
	else if (len == 0) {
		ret = EOK;
	}
	else {
		ret = mtd->ops->point(mtdInfo->storage, from, len, retlen, virt, phys);
	}
	
	return ret;
```

2022-04-12 11:20 UTC, agkaminski commented on libmtd/mtd.c
> +	return mtd->ops->point(mtdInfo->storage, from, len, retlen, virt, phys);
Most other cases can be rearranged in a similar fasion

2022-04-12 12:15 UTC, HBuczynski commented on libmtd/mtd.c
> +	}
Applied Your suggestion.

2022-04-12 14:16 UTC, agkaminski commented on libmtd/mtd.c
> +		ret = mmap(NULL, *size, PROT_READ | PROT_WRITE, MAP_ANONYMOUS, OID_CONTIGUOUS, 0);
Won't work for `*size != n * _PAGE_SIZE`. We need to align `*size` both to `mtdInfo->writesize` and `_PAGE_SIZE`.

2022-04-12 14:16 UTC, agkaminski commented on libmtd/mtd.c
> +	}
Do we need aligned physical or virtual addresses?

2022-04-12 14:18 UTC, agkaminski commented on libmtd/mtd.c
> +	if (mtdInfo->writesize < _PAGE_SIZE) {
```suggestion
	if (mtdInfo->writesize <= _PAGE_SIZE) {
```

2022-04-20 09:26 UTC, agkaminski approved these changes

2022-04-20 10:42 UTC, merged